/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminTiersRouteImport } from './routes/admin.tiers'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTiersRoute = AdminTiersRouteImport.update({
  id: '/admin/tiers',
  path: '/admin/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/tiers': typeof AdminTiersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/tiers': typeof AdminTiersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/tiers': typeof AdminTiersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/audit' | '/admin/promotions' | '/admin/tiers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/audit' | '/admin/promotions' | '/admin/tiers'
  id: '__root__' | '/' | '/admin/audit' | '/admin/promotions' | '/admin/tiers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminTiersRoute: typeof AdminTiersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tiers': {
      id: '/admin/tiers'
      path: '/admin/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AdminTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminTiersRoute: AdminTiersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
